package com.EduAdminSysProject.dao;

import com.EduAdminSysProject.dataobject.CourseDO;
import com.EduAdminSysProject.dataobject.CourseDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CourseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int deleteByPrimaryKey(@Param("cid") String cid, @Param("gid") String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int insert(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int insertSelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    CourseDO selectByPrimaryKey(String cid, String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int updateByPrimaryKeySelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int updateByPrimaryKey(CourseDO record);

    List<CourseDO> selectCourseByGid(@Param("gid") String gid);
}