package com.EduAdminSysProject.dao;

import com.EduAdminSysProject.dataobject.CourseDO;

import java.util.List;

public interface CourseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int insert(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int insertSelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    CourseDO selectByPrimaryKey(String cid);

    List<CourseDO> selectAllCourses();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int updateByPrimaryKeySelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int updateByPrimaryKey(CourseDO record);
}