package com.EduAdminSysProject.dao;

import com.EduAdminSysProject.dataobject.GradeDO;
import com.EduAdminSysProject.dataobject.GradeDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GradeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int deleteByPrimaryKey(GradeDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int insert(GradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int insertSelective(GradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    GradeDO selectByPrimaryKey(String sid, String gid);

    List<GradeDO> selectAllChosenCourse(@Param("sid") String sid, @Param("gid") String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int updateByPrimaryKeySelective(GradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int updateByPrimaryKey(GradeDO record);
}