package com.EduAdminSysProject.dao;

import com.EduAdminSysProject.dataobject.GradeDO;
import com.EduAdminSysProject.dataobject.GradeDOKey;

import java.util.List;

public interface GradeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int deleteByPrimaryKey(GradeDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int insert(GradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int insertSelective(GradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    GradeDO selectByPrimaryKey(GradeDOKey key);

    List<GradeDO> selectAllChosenCourse(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int updateByPrimaryKeySelective(GradeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int updateByPrimaryKey(GradeDO record);
}