package com.EduAdminSysProject.dao;

import com.EduAdminSysProject.dataobject.UserpasswordDO;

public interface UserpasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int insert(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int insertSelective(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    UserpasswordDO selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int updateByPrimaryKeySelective(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    int updateByPrimaryKey(UserpasswordDO record);
}