package com.EduAdminSysProject.dao;

import com.EduAdminSysProject.dataobject.UserDO;
import com.EduAdminSysProject.dataobject.UserDOKey;
import org.apache.ibatis.annotations.Param;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int deleteByPrimaryKey(UserDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    UserDO selectByPrimaryKey(@Param("sid") String sid, @Param("gid") String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int updateByPrimaryKey(UserDO record);
}