package com.EduAdminSysProject.dao;

import com.EduAdminSysProject.dataobject.UserpasswordDO;
import com.EduAdminSysProject.dataobject.UserpasswordDOKey;
import org.apache.ibatis.annotations.Param;

public interface UserpasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int deleteByPrimaryKey(String sid, String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int insert(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int insertSelective(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    UserpasswordDO selectByPrimaryKey(@Param("sid") String sid, @Param("gid") String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int updateByPrimaryKeySelective(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    int updateByPrimaryKey(UserpasswordDO record);
}