package com.EduAdminSysProject.dataobject;

public class CourseDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.cId
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.description
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.cId
     *
     * @return the value of course_info.cId
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.cId
     *
     * @param cid the value for course_info.cId
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.description
     *
     * @return the value of course_info.description
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.description
     *
     * @param description the value for course_info.description
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}