package com.EduAdminSysProject.dataobject;

public class CourseDO extends CourseDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.description
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.description
     *
     * @return the value of course_info.description
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.description
     *
     * @param description the value for course_info.description
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}