package com.EduAdminSysProject.dataobject;

public class CourseDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.cId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.gId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    private String gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.cId
     *
     * @return the value of course_info.cId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.cId
     *
     * @param cid the value for course_info.cId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.gId
     *
     * @return the value of course_info.gId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.gId
     *
     * @param gid the value for course_info.gId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }
}