package com.EduAdminSysProject.dataobject;

public class GradeDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.sId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.cId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    private String gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.sId
     *
     * @return the value of grade.sId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.sId
     *
     * @param sid the value for grade.sId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.cId
     *
     * @return the value of grade.cId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.cId
     *
     * @param cid the value for grade.cId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gId
     *
     * @return the value of grade.gId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gId
     *
     * @param gid the value for grade.gId
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }
}