package com.EduAdminSysProject.dataobject;

public class GradeDO extends GradeDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    private Integer grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade
     *
     * @return the value of grade.grade
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade
     *
     * @param grade the value for grade.grade
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
}