package com.EduAdminSysProject.dataobject;

public class UserpasswordDO extends UserpasswordDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encryptPassword
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    private String encryptpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encryptPassword
     *
     * @return the value of user_password.encryptPassword
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public String getEncryptpassword() {
        return encryptpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encryptPassword
     *
     * @param encryptpassword the value for user_password.encryptPassword
     *
     * @mbg.generated Tue May 28 20:46:39 CST 2019
     */
    public void setEncryptpassword(String encryptpassword) {
        this.encryptpassword = encryptpassword == null ? null : encryptpassword.trim();
    }
}