package com.EduAdminSysProject.dataobject;

public class UserpasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.sId
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encryptPassword
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    private String encryptpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.sId
     *
     * @return the value of user_password.sId
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.sId
     *
     * @param sid the value for user_password.sId
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encryptPassword
     *
     * @return the value of user_password.encryptPassword
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public String getEncryptpassword() {
        return encryptpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encryptPassword
     *
     * @param encryptpassword the value for user_password.encryptPassword
     *
     * @mbg.generated Sun May 26 20:17:20 CST 2019
     */
    public void setEncryptpassword(String encryptpassword) {
        this.encryptpassword = encryptpassword == null ? null : encryptpassword.trim();
    }
}